# Generated by Django 3.2.4 on 2021-06-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_rate_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.EmailField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('message', models.TextField(max_length=2048)),
            ],
        ),
    ]
